### ISSUE TITLE
Close PDF window when esc key pressed

### ISSUE THREAD

**Issue by rajlego** [supermemo/SuperMemoAssistant.Plugins.PDF#116]
Currently, to close PDF window, you have to use the mouse (horrid) or press alt+f4 (not likely to seem obvious to many people and also makes me nervous of closing SM by accident instead).

Esc closing it would be ideal and likely what people would expect from how other windows in SM work.

**Comment by alexis-** [comment]
Moved to the appropriate repository.

I don't think I'll implement that. You can just alt-tab if you want to go to SM, or press alt-f4. It would be very annoying if the window closed at the press of a single key. SuperMemo's design isn't ideal in that specific aspect.
