### ISSUE TITLE
Extracted text keep the color change even the extracted item is deleted. makes ppl annoying.

### ISSUE THREAD

**Issue by ccchan234** [supermemo/SuperMemoAssistant.Plugins.PDF#129]
#### Description
A clear and concise description of the issue you are experiencing. Remember, this is not a place to ask questions. For that, go to https://discord.gg/vUQhqCT.

Extracted text keep the color change even the extracted item is deleted. makes ppl annoying.

#### Steps to Reproduce
Tell us how to reproduce this issue.

alt+x to extract some text, then delete that item.

#### Expected behavior

the previously extracted but now not extracted text should return to normal text (i.e. not highlighted)

#### Logs, Screenshots, ...
If applicable, add relevant files:
- Logs (`My Documents\SuperMemoAssistant\Logs`)
- Screenshots
- Videos
- Contextual files [e.g. SM Collection, PDF document, LaTeX formula]
![image](https://user-images.githubusercontent.com/37549409/214094788-70c106e1-8a7b-4dc3-9543-78324e5123c3.png)

#### Environment (fill where applicable)
- **Version**: [e.g. SMA 2.0.4.89, PDF Plugin 2.0.4.10]
SMA 2.1.0 beta.21, PDF plugin 2.1.0 beta 14

- **Last version that did not exhibit the issue**:
- **SM Version**: [e.g. SM 18.04]
- SM 18.05
- **OS**: [e.g. Windows 10 64bit]
- **OS Language**: [e.g. English (UK), French (FR)]
- **Browser**: [e.g. Chrome 68, Safari 45]

**Comment by conrad994** [comment]
I have the same question as yours, is there a solution?

**Comment by ccchan234** [comment]
i gave up on SM, too little ppl use it, and not open source means you cant change it.

i'll say supermemo could survive if they SELL their SM18 as a module and use it inside anki?
somehow make some license protection for that module.
