### ISSUE TITLE
How to run PDF plugin?

### ISSUE THREAD

**Issue by vts3rss** [supermemo/SuperMemoAssistant.Plugins.PDF#27]
Hi there!
Please tell -- how to run PDF plugin? I have already run legacy SupermemoAssistant, but what to do next? Ctrl+Win+i doesn't work.

**Comment by alexis-** [comment]
Hello,

You need the new SuperMemoAssistant which you can find here https://github.com/supermemo/SuperMemoAssistant.
You have to compile it yourself for now, until the beta starts.

**Comment by luislopes7** [comment]
hello,

I need to know how to compile SMA in order to run the pdf plugin.
I ask if there is any way to run the plugin with a script, in the same way that the supermemo occlussion is executed, which works very well for me.

thanks for your work, the oclussion plugin It helped me a lot

**Comment by luislopes7** [comment]
Hi, i am still waiting how to compile SMA to run pdf plugin and image oclussion. Sorry but i am not a programer because of that i need help to compile

**Comment by alexis-** [comment]
Please check https://github.com/supermemo/SuperMemoAssistant for instructions.
