### ISSUE TITLE
image selection of text fragments

### ISSUE THREAD

**Issue by fkgruber** [supermemo/SuperMemoAssistant.Plugins.PDF#30]
Hi
When reading technical documents we often have math inline with text. I don't see any way to select the math inside a paragraph as image. It is treated as text.

Ideally I would like to run the OCR on the inline math but again this is not possible right now since there is no way to force image selection inside a text paragraph

thanks

**Comment by alexis-** [comment]
This is a tricky issue. Force image selection will be introduced soon as a quick remedy.

**Comment by alexis-** [comment]
Fixed in latest commit https://github.com/supermemo/SuperMemoAssistant.Plugins.PDF/commit/78268401b854c6c987d2527d0e26dc5777957a7f with right-click forced image area selection
