### ISSUE TITLE
Image selection problem in some pdfs

### ISSUE THREAD

**Issue by fkgruber** [supermemo/SuperMemoAssistant.Plugins.PDF#31]
I have found some issues with certain pdfs where you are unable to select images.
For example when I click and drag to try to select an image I get a whole band selected or in some cases a whole page.
![image](https://user-images.githubusercontent.com/4311763/63542327-2398fc80-c4ee-11e9-94b7-1fc421c104c6.png)

I'm attaching an example
[testreg2.pdf](https://github.com/supermemo/SuperMemoAssistant.Plugins.PDF/files/3531544/testreg2.pdf)

**Comment by alexis-** [comment]
Hello,

The PDF you provided has laid out the images in the way your screenshot demonstrates.
The top figure is split in two images, the top one includes the "CLASSICAL HYPOTHESIS TESTING" and the top of the graphic, while the bottom one is as above minus the legend.
The legend is included as text.

Different PDF have different ways of arranging their content. Some are more efficient/qualitative than other in terms of how easy they allow extracting information.

For this kind of situation, you can use the image area selection (manually drag your mouse over a region while holding the left button), and then use Ctrl to append the legend text to your selection.

As of now this might be problematic as the image layer will be selected when you click. In a subsequent version, I will introduce the possibility of forcing the image area selection mode regardless of where you are clicking.

**Comment by alexis-** [comment]
Fixed in latest commit https://github.com/supermemo/SuperMemoAssistant.Plugins.PDF/commit/78268401b854c6c987d2527d0e26dc5777957a7f with right-click forced image area selection
