### ISSUE TITLE
Improve interaction with concepts

### ISSUE THREAD

**Issue by jordancurve** [supermemo/SuperMemoAssistant.Plugins.PDF#35]
I use concepts to organize my knowledge tree, and I have two issues with the way the SMA PDF plugin deals with concepts.

To begin with, I should explain that I have all my PDFs under a single "PDFs" concept element directly under the root of my knowledge tree.

My first issue occurs after I click Learn and a PDF comes up. Suppose, as is common, that the default concept (next to the light bulb in the Elements window) is something other than "PDFs". For example, suppose I was making some "Math" concept elements before I clicked Learn. Now, whenever I try to make an extract from the PDF, I get this error:

```
Concept verification
Hook not a child of root!
```

To work around this error, whenever a PDF appears in learning, I switch the focus to the element window, make sure the default concept is "PDFs", and then switch back to the PDF window. Maybe my feature request here is for SMA to do those steps for me automatically, and also, when I move on from the PDF, to change the default concept back to what it was before.

My second issue is that I wish I didn't have to keep all my PDFs under one top-level concept. I wish I could organize them under the concept that they actually belong under.

**Comment by alexis-** [comment]
> My first issue occurs after I click Learn and a PDF comes up. Suppose, as is common, that the default concept (next to the light bulb in the Elements window) is something other than "PDFs". For example, suppose I was making some "Math" concept elements before I clicked Learn. Now, whenever I try to make an extract from the PDF, I get this error:
> 
> ```
> Concept verification
> Hook not a child of root!
> ```

Per-PDF concepts will be implemented in the future.

> My second issue is that I wish I didn't have to keep all my PDFs under one top-level concept. I wish I could organize them under the concept that they actually belong under.

What currently prevents you from doing so, aside from having to change the current concept in SM ?

**Comment by jordancurve** [comment]
> What currently prevents you from doing so, aside from having to change the current concept in SM ? 

Nothing; that’s the only reason.

If I understand correctly, in order to make extracts from PDFs that have been organized under separate concepts, I would have to perform the following steps each time a new PDF comes up in learning:

1. switch from the PDF window to the Element window
2. figure out the correct concept of the current PDF
3. click the lightbulb icon in the element window 
4. Type in the name of the PDF’s concept
5. switch back to the PDF window

It’s easier just to set the default concept to “PDFs” before I start learning.

**Comment by alexis-** [comment]
Popup issue fixed. Elements still aren't linked to concept though, seems more complicated than anticipated.
https://github.com/supermemo/SuperMemoAssistant.Plugins.PDF/commit/dd564d04da13a49adb0e3b74ab2c0264c110351a
